# Start XDG autostart .desktop files using dex. See also
# https://wiki.archlinux.org/index.php/XDG_Autostart
exec --no-startup-id dex --autostart --environment i3

# The combination of xss-lock, nm-applet and pactl is a popular choice, so
# they are included here as an example. Modify as you see fit.

# xss-lock grabs a logind suspend inhibit lock and will use i3lock to lock the
# screen before suspend. Use loginctl lock-session to lock your screen.
#exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork
exec --no-startup-id xset s off     # Prevent Screen sleep
exec --no-startup-id xset -dpms     # Prevent Power Saving

# NetworkManager is the most popular way to manage wireless networks on Linux,
# and nm-applet is a desktop environment-independent system tray GUI for it.
### Just use nmtui(NetworkManager) or impala(iwd) ###
#exec --no-startup-id nm-applet

# Disable Mouse Acceleration
# https://wiki.archlinux.org/index.php/Mouse_acceleration
# or you can set manual by replace "$()" with id of your mouse.
exec_always --no-startup-id xinput set-prop "$(xinput | grep 'HyperX' | grep -v 'Keyboard' | awk -F'id=' '{print $2}' | awk '{print $1}')" "libinput Accel Profile Enabled" 0 1 0
# Set xrandr
#exec_always --no-startup-id ~/.config/i3/xrandr.sh
# Start Notification Deamon
exec --no-startup-id dunst
# Wallpaper restore
exec --no-startup-id ~/.config/i3/fehbg.sh
# Startup autotiling
exec_always --no-startup-id autotiling
# Execute polkit
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# Execute picom
#exec --no-startup-id picom
# Setup keyboard layout
exec_always --no-startup-id "setxkbmap -layout us,th -option grp:ctrl_space_toggle"
# Execute clipmenu
exec --no-startup-id clipmenud
# Execute udiskie
exec --no-startup-id udiskie
# Keyeing
exec --no-startup-id /usr/bin/gnome-keyring-daemon --start
# Openfortivpn (Optional: Need to add openfortivpn in sudoers first)
#exec --no-startup-id "sudo /usr/bin/openfortivpn"