icons_format = "{icon}"

[theme]
theme = "native"
[theme.overrides]
idle_bg = "#222222"
idle_fg = "#ffffff"

[icons]
icons = "awesome6"
[icons.overrides]
#bat = ["|E|", "|_|", "|=|", "|F|"]
#bat_charging = "|^| "

[[block]]
block = "focused_window"
[block.format]
full = " $title.str() |"
#short = " $title.str() |"

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:20)  $prev $play $next |}"
player = "spotify"

#[[block]]
#block = "keyboard_layout"
#driver = "setxkbmap"
#interval = 15

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "net"
format = " $icon {$ssid|NO INTERNET}"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
