# Title format
#for_window [class=".*"] title_format "<b>%title</b>"
for_window [class=".*"] title_format "<b>%title</b> <i>%class</i>"
for_window [all] title_window_icon on
for_window [all] title_window_icon padding 3px

# Floating must float windows
for_window [class="Pavucontrol"] floating enable
for_window [title="Friends List"] floating enable
for_window [title="Steam Settings"] floating enable
for_window [class="Nitrogen"] floating enable
for_window [title="LINE"] floating enable
for_window [class="Nemo"] floating enable
for_window [class="Blueman-manager"] floating enable

for_window [title="Add New Items"] floating enable
for_window [title="Panel Preferences"] floating enable
for_window [title="Separator"] floating enable
for_window [class="Xfce4-about"] floating enable
for_window [class="Xfce4-appfinder"] floating enable
for_window [class="Thunar"] floating enable
for_window [class="polkit-ukui-authentication-agent-1"] floating enable
for_window [class="Captain.py"] floating enable
