# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.

#workspace 1 output primary
#workspace 2 output primary
#workspace 3 output primary
#workspace 4 output primary
#workspace 5 output primary

# floating workspace
#for_window [class=".*"] floating enable
#for_window [class="Picture in picture"] sticky enable

# Borders
default_border normal
default_floating_border normal
#default_border pixel 3
gaps inner 10px
gaps outer 10px

# Title format
for_window [class=".*"] title_format "%class -> <b>%title</b>"
for_window [all] title_window_icon on
for_window [all] title_window_icon padding 3px

# Floating must float windows
for_window [class="pavucontrol"] floating enable
for_window [title="Friends List"] floating enable
for_window [title="Steam Settings"] floating enable
