# Execute your favorite apps at launch
exec-once = systemctl --user start hyprpolkitagent
exec-once = waybar &
exec-once = hyprpaper &
exec-once = udiskie &
exec-once = mako &
#exec-once = nm-applet  # Use iwd + impala instead
exec-once = wl-paste --watch cliphist store
exec-once = waypaper --restore
exec = hyprshade on vibrance  # If want more vibrance. Uncomment this
exec-once = nwg-dock-hyprland -i 36 -w 5 -nolauncher -r -p right -mr 10

# Prefer Dark mode
# https://wiki.archlinux.org/title/Dark_mode_switching 
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

# Set Launc at Login app
#exec-once = discord && hyprctl dispatch movetoworkspace 1  # If using original Discord
#exec-once = steam && hyprctl dispatch movetoworkspace 3
