# All workspace is float; If want tiling, comment all this
windowrule = match:class (.*), float on
# Float remember size
windowrule = match:class (.*), persistent_size on

# Float by windows
#windowrule = float, class:^(org.pulseaudio.pavucontrol)$
#windowrule = float, class:^(waypaper)$
#windowrule = float, class:^(nwg-look)$
#windowrule = float, class:^(eog)$
#windowrule = float, class:^(steam)$,title:^(Steam - Self Updater)$
#windowrule = float, class:^(steam)$,title:^(Steam Settings)$
#windowrule = tile, class:^(WebApp-.*)$

# Set windows will landing in workspace
#windowrulev2 = workspace 1, class:^(discord)$
#windowrulev2 = workspace 1, class:^(steam)$

# Set custom size for some windows not remember size
#windowrulev2 = size 50% 60%, class:^(kitty)$
#windowrulev2 = size 60% 70%, class:^(thunar)$

# FROM CACHYOS
# Float Necessary Windows
#windowrule = float,class:^(nemo)$
#windowrule = float,class:^(blueman-manager)$
#windowrule = float,class:^(iwdgui)$
#windowrule = float, class:^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$
#windowrule = float, class:^(polkit-gnome-authentication-agent-1|hyprpolkitagent|org.org.kde.polkit-kde-authentication-agent-1)(.*)$
#windowrule = float,class:^(zenity)$
