# Example windowrule v1
#windowrule = float,^(pavucontrol)$
# Example windowrule v2
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# All workspace is float; If want tiling, comment all this
windowrulev2 = float, workspace:1
windowrulev2 = float, workspace:2
windowrulev2 = float, workspace:3
windowrulev2 = float, workspace:4
windowrulev2 = float, workspace:5

# Float by windows
windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
windowrulev2 = float, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = float, class:^(steam)$
windowrulev2 = float, class:^(Spotify)$
windowrulev2 = float, class:^(waypaper)$
windowrulev2 = float, class:^(vlc)$
windowrulev2 = float, class:^(nwg-look)$
windowrulev2 = float, class:^(eog)$
windowrulev2 = float, class:^(io.mrarm.mcpelauncher-ui-qt)$

# Set windows will landing in workspace
#windowrulev2 = workspace 3, class:^(discord)$
#windowrulev2 = workspace 3, class:^(steam)$

# Set custom size for some windows not remember size
windowrulev2 = size 50% 60%, class:^(kitty)$
windowrulev2 = size 60% 70%, class:^(thunar)$

# FROM CACHYOS
# Float Necessary Windows
windowrulev2 = float,class:^(blueman-manager)$
windowrulev2 = float,class:^(xdg-desktop-portal-gtk)$
windowrulev2 = float,class:^(xdg-desktop-portal-kde)$
windowrulev2 = float,class:^(xdg-desktop-portal-hyprland)$
windowrulev2 = float,class:^(zenity)$
windowrulev2 = float,class:^()$,title:^(Steam - Self Updater)$
