# All workspace is float; If want tiling, comment all this
#windowrule = match:class (.*), float on
# Float remember size
windowrule = match:class (.*), persistent_size on

# Float by windows
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, float on
windowrule = match:class ^(waypaper)$, float on
windowrule = match:class ^(nwg-look)$, float on
windowrule = match:class ^(eog)$, float on
windowrule = match:title ^(Steam - Self Updater)$, float on
windowrule = match:title ^(Steam Settings)$, float on
windowrule = match:class ^(WebApp-.*)$, float on

# FROM CACHYOS
# Float Necessary Windows
windowrule = match:class ^(nemo)$, float on
windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(iwdgui)$, float on
windowrule = match:class ^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$, float on
windowrule = match:class ^(polkit-gnome-authentication-agent-1|hyprpolkitagent|org.org.kde.polkit-kde-authentication-agent-1)(.*)$, float on
windowrule = match:class ^(zenity)$, float on
